config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :lists do
    resources :items
  end

  namespace :api, defaults: { format: :json } do
    resources :users do
      resources :lists, only: [:index]
    end

    resources :lists do
      resources :items
    end

    resources :items, only: [:destroy]
  end

  authenticated :user do
    root 'users#show', as: :authenticated_root
  end

  root 'welcome#index'
end

# api/users
# api/users/:id
# api/users/:user_id/lists
# api/users/:user_id/lists/:id
# api/lists
# api/lists/:id
# api/lists/:list_id/items
# api/lists/:list_id/items/:id
# DELETE api/items/:id

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_auth_token

  private

  def generate_auth_token
    begin
      self.auth_token = SecureRandom.hex
    end while self.class.exists?(auth_token: auth_token) # to ensure that the auth_token is unique
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  def days_left
    7 - ((Time.now.to_i - self.created_at.to_i) / 86400)
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items

  before_save { self.permissions ||= :closed }

  enum permissions: [:closed, :open, :viewable]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists

  before_create :generate_auth_token

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.hex
      break unless User.find_by(auth_token: auth_token)
    end
  end

  def serialize
    hash = {}
    attributes.each { |key, val| hash[key] = val }
    hash
  end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController
  before_action :authenticated?

  def create
    item = Item.new(item_params)
    if item.save
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      render json: item
    else
      render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:content, :list_id, :completed)
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController
  before_action :authenticated?

  def index
    render json: List.all
  end

  def create
    list = List.new(list_params)

    authorize list

    list.user = current_user
      if list.save
        render json: list
      else
        render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
      end
  end

  def update
    list = List.find(params[:id])

    authorize list

    if list.update(list_params)
      render json: list
    else
      render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      list = List.find(params[:id])
      authorize list
      list.destroy

      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render :json => {}, :status => :not_found
    end
  end

  private

  def list_params
    params.require(:list).permit(:title,:description,:user_id,:permissions)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  before_action :authenticated?

  def index
    return permission_denied_error unless conditions_met

    users = User.all

    render json: users, each_serializer: UserSerializer
  end

  def show
    user = User.find(params[:id])

    render json: user
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      user = User.find(params[:id])
      user.destroy

      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render :json => {}, :status => :not_found
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:password,:email)
  end

  def conditions_met
    true
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  respond_to :json

  private

  def authenticated?
    authenticate_or_request_with_http_token do |token, options|
      @current_user = User.find_by(auth_token: token)
    end
  end

  def permission_denied_error
    error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
    response = {
      response_type: "ERROR",
      message: message
    }

    render json: respond.to_json, status: status
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list

  def create
    @item = @list.items.create(item_params)
    @item.list = @list
    redirect_to @list
  end

  def destroy
    @item = @list.items.find(params[:id])
    if @item.destroy
      flash[:success] = "To-Do list item was deleted."
    else
      flash[:error] = "To-Do list item could not be deleted."
    end
    redirect_to @list
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @item }
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def item_params
    params[:item].permit(:content)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @list }
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    if @list.save
      flash[:notice] = "To-do list was saved."
      redirect_to @list
    else
      flash.now[:alert] = "There was an error saving the To-do list. Please try again."
      render :new
    end
  end

  def edit
    @lists = current_user.lists
  end

  def update
    @list.assign_attributes(list_params)

    if @list.save
      flash[:notice] = "To-do list was updated."
      redirect_to @list
    else
      flash.now[:alert] = "There was an error updating the To-do list. Please try again."
      render :edit
    end
  end

  def destroy
    if @list.destroy
      flash[:notice] = "To-do list was deleted."
      redirect_to lists_path
    else
      flash.now[:alert] = "There was an error deleting the To-do list. Please try again."
      render :show
    end
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for([@list, @list.items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<div class="item">
  <p><%= item.content %>
  <%= link_to "", list_item_path(@list,item.id), method: :delete, class: 'glyphicon glyphicon-ok' %>
  <small>
    <i><%= item.days_left %> days left to finish!</i>
  </small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reminder App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <div id = "notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<% elsif alert %>
  <div id = "notice_wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

<nav class= "navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Reminder App", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class= "nav navbar-nav navbar-right">
        <div id="user-navlinks">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.name %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/create.html.erb
<h1>List#create</h1>
<p>Find me in app/views/list/create.html.erb</p>

app/views/lists/edit.html.erb
<h1 class="list_title">Edit To-do List</h1>

<div class="forms">
  <%= render 'form'%>
</div>

<div class="links">
  <%= link_to "Back", lists_path %>
</div>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <div class="index_row clearfix">
    <h2 class="list_title"><%= link_to list.title, list %></h2>
    <p class="description"><%= list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "Create a New List", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1 class="list_title">New To-do List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to "Back", lists_path %>
</div>

app/views/lists/show.html.erb
<% if current_user == @list.user %>
  <h2 class="list_title"><%= @list.title%></h2>
  <h4 class="description"><%= @list.description%></h4>

  <div id ="items_wrapper">
    <%= render @list.items %>

    <%= render "items/form" %>
  </div>

  <div class="links">
    <%= link_to 'Edit', edit_list_path(@list) %> |
    <%= link_to 'Delete', list_path(@list), method: :delete, data: { confirm: "Are you sure?" } %> |
    <%= link_to 'Back', lists_path %>
  </div>
<% else %>
  <p class="description">
    Sorry, this to-do list is <b>private</b> to the list creator
  </p>
  <div class="links">
    <%= link_to 'Go Back', lists_path %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1 class="list_title">Welcome, <%= current_user.username %>!</h1>
<p class="description"><i>Goal without a plan is just a wish. Stop waiting, & start doing!<br />
Let's get things done!</p></i>

<div class="links">
  <%= link_to "New To-Do List", new_list_path %><br />
  <%= link_to "View To-Do Lists", lists_path %>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron vertical-center">
  <h1 class="header">Reminder</h1>
  <h4>A timed self-deleting To-Do List App that helps you <i>always</i> remember to finish the important tasks</h4>
  <p>Start creating weekly reminders to increase your productivity!</p>
  <%= link_to "Create an Account", new_user_registration_path, class: 'btn btn-info'%>
</div>